### ISSUE TITLE
Kafka Scaler with both SASL and SSL(TLS)

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#1043]
_First of all I'd like to say, that I am not a Kafka expert._

Currently there's no way, how to set both `SSL` (cert, key, cacert) and `SASL` (username, password) for client in Kafka scaler, look at the code below:
https://github.com/kedacore/keda/blob/bf25619a6d920df27a7f56607f87667d7b23aa1b/pkg/scalers/kafka_scaler.go#L144-L173

There are several options for [Authentication of Kafka Scaler](https://keda.sh/docs/1.5/scalers/apache-kafka/#authentication-parameters), but I haven't found a one, that allows me to specify both.

Is this a correct behavior? IMHO it should be possible to specify both.

**Comment by ansonauhk** [comment]
I have a fix working and going to push

**Comment by ppatierno** [comment]
@zroubalik from what I see here

https://github.com/kedacore/keda/blob/bf25619a6d920df27a7f56607f87667d7b23aa1b/pkg/scalers/kafka_scaler.go#L201

it's supported by mixing SSL with other SASL mechanisms for authentication like PLAINTEXT and SCRAM-SHA with both username and password. It's also possible to use SSL client authentication using the certificates.
Said that ... I really think that both codes need a refactoring because I can understand that it's not clear.
Enabling SSL is a different thing than enabling a specific SASL authentication mechanism.
At scaler level configuration I would differentiate them in two different parameters (encryption/tls and authentication) instead of having these `kafkaAuthModeForXXXXX` const trying to mix every single way.

**Comment by zroubalik** [comment]
> At scaler level configuration I would differentiate them in two different parameters (encryption/tls and authentication) instead of having these `kafkaAuthModeForXXXXX` const trying to mix every single way.
+1 that code is a mess

OK, but while looking at the code, the only authmode where you can specify certificates is in this if block `metadata.authMode == kafkaAuthModeForSaslSSL`, but for this authmode, you can't specify username and password.
https://github.com/kedacore/keda/blob/bf25619a6d920df27a7f56607f87667d7b23aa1b/pkg/scalers/kafka_scaler.go#L224
