### ISSUE TITLE
CPU/Memory scalers not working in 2.0.0-rc

### ISSUE THREAD

**Issue by knepe** [kedacore/keda#1275]
I'm trying to test out the cpu/memory scalers, but its keda-operator does not seem to recognize it. 
Im getting this in the logs: 
`2020-10-20T06:32:27.721Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "keda.sh", "reconcilerKind": "ScaledObject", "controller": "scaledobject", "name": "scaled-obj-name", "namespace": "default", "error": "error getting scaler for trigger #0: no scaler found for type: cpu"}`

I guess it might be that this https://github.com/kedacore/keda/pull/1215 is not released yet, even though it is in the docs?

## Expected Behavior
CPU/Memory scalers working

## Actual Behavior
CPU/Memory scalers not working

## Steps to Reproduce the Problem

  1. Add ScaledObject with cpu trigger

## Specifications

  - **KEDA Version:** *v2.0.0-rc*
  - **Platform & Version:** *Please elaborate*
  - **Kubernetes Version:** *1.16*
  - **Scaler(s):** *cpu/memory*

**Comment by zroubalik** [comment]
Yeah, it is not a part of RC, we are gonna release RC2 soon (in a matter of days), which will contain this scaler.

**Comment by kenotsolutions** [comment]
> Yeah, it is not a part of RC, we are gonna release RC2 soon (in a matter of days), which will contain this scaler.

Thanks for the update,

I was testing and got the same error. When can you **release** it?

**Comment by zroubalik** [comment]
@kenotsolutions once this is fixed https://github.com/kedacore/keda/issues/1257

**Comment by zroubalik** [comment]
FYI RC2 is out

**Comment by bwkerbow** [comment]
@zroubalik Fantastic and quick, thanks. I had this same issue and just installed RC2 into my cluster in hopes of scaling off of CPU. 

I know it is just an RC, but if you/y'all are not already aware, it seems as though creating ScaledObjects does not create an HPA resources in RC2. That issue was not present in the 1.5.0 release, but I'm assuming the issue will be fixed in the real 2.0.0 release. Please correct me if I'm wrong, I'm happy to create a more detailed issue if needed.
