### ISSUE TITLE
Add validation of submitted .yaml files for scalers

### ISSUE THREAD

**Issue by jeffhollan** [kedacore/keda#179]
Inspired by this issue https://github.com/kedacore/keda/pull/177 and a suggestion to potentially use https://github.com/apps/kubevalidator

**Comment by tomkerkhove** [comment]
You can assign this to me

**Comment by tomkerkhove** [comment]
Since this is not working smoothly yet due I'm wondering if we should maybe leave it out for now until we've fixed the config issue and it does not work nicely with custom resources & Helm.

Or is this not bothering you @ahmelsayed? Not sure if it has any value if those are not covered.

_I wasn't aware of that, my bad_

**Comment by ahmelsayed** [comment]
Sorry for the delay in getting to this. I'll remove kubevalidator for now until either this https://github.com/urcomputeringpal/kubevalidator/issues/57 is available or we find a way to make it not always fail. 

https://github.com/kedacore/keda/pull/363

**Comment by tomkerkhove** [comment]
Agreed, sorry for that!
