### ISSUE TITLE
Why should we use KEDA if we are already use Azure Functions in Azure?

### ISSUE THREAD

**Issue by David-Stark** [kedacore/keda#219]
Hello!

I find KEDA to be a very interesting, but can you explain to me why should we use KEDA if we are already use Azure Functions in Azure?

Thanks in advance!

**Comment by tomkerkhove** [comment]
Because you might want to move your application to Kubernetes and run it alongside your other apps inside the cluster.

It depends on how much control and alignment you want to have.

**Comment by joshdcar** [comment]
@David-Stark  -  My Two Cents - It's all about your workload. I firmly believe that the Azure Function Service should be the first place you go to run Azure Functions on Azure but if you run into a use case where you are running into blockers due to limitations of the service then you now have the flexibility of running that workload in an environment that gives you more knobs and dials (e.g. your workload would benefit from GPU optimized VMs). Key here is if you require it.  So essentially you still want the productivity gain you get from the Azure Functions framework but you need more control with the environment and with KEDA you now get that flexibility alongside all the potentially scaling and cost benefits of cloud native Serverless (scale to zero, etc).

**Comment by tomkerkhove** [comment]
Agreed!

**Comment by David-Stark** [comment]
Thanks for the fast responses! 

I think I understand now the idea with KEDA. Thanks very much =)

**Comment by jeffhollan** [comment]
Going to close this but in addition to these here's the big 4 we talk about:

- Want to run functions on-premises (potentially in something like an 'intelligent edge' architecture)
- Want to run functions alongside other Kubernetes apps (maybe in a restricted network, app mesh, custom environment, etc.)
- Want to run functions outside of Azure (no vendor lockin)
- Specific need for more control (GPU enabled compute clusters, more knobs and such)

**Comment by jeffhollan** [comment]
This should likely pop up in the FAQ assigned to @anirudhgarg  though #170
