### ISSUE TITLE
Dynamically select the value of TargetRef for ScaledJob based on trigger metadata

### ISSUE THREAD

**Issue by matt-psaltis** [kedacore/keda#2204]
### Proposal

Right now, ScaledJobs are executed based on a hard coded target definition either by jobTargetRef or scaleTargetRef. I'm looking for a way to select the target based on trigger metadata. For example, if the MSSQL trigger query looks like this:

query: "SELECT COUNT(*) AS Count, Target FROM backlog WHERE state='running' OR state='queued'"
Then the jobTargetRef or scaleTargetRef could use the value of Target to select the job definition to execute.

### Use-Case

This will simplify our trigger and scaleobject definitions to a single definition for all background processes.

In our ecosystem we would like a centralised trigger system / definition for all jobs but allow the job that is executed to be arbitrary based on additional information provided by the trigger.

**Comment by JorTurFer** [comment]
Hi
I think that this is not possible right now because metrics are recovered in the same way for ScaledObject and ScaledJobs (Basically it's the return of `scaler.GetMetrics()`).
This change requires splitting the current behavior in 2 different, and not all scalers will support it. 
Something "similar" was discussed [here](https://github.com/kedacore/keda/issues/2105) and the decision was that it's out of the roadmap. 
Am I right @zroubalik ?
