### ISSUE TITLE
Azure Storage Queue scaler is reporting wrong number of messages in queue

### ISSUE THREAD

**Issue by jungopro** [kedacore/keda#2385]
### Report

Hello
I think the azure_queue monitor is not reading the number of messages in the queue as it should
Looking at the code [here](https://github.com/kedacore/keda/blob/main/pkg/scalers/azure/azure_queue.go) I think that when Keda calculates the "visible messages" as 0 it returns 0, even though the actual number of messages in the queue is much higher

For example:
We see "showing 0 of 128503 messages in queue" in the portal, and Keda is also reporting 0 for the metric (even though the actual count is 128k) - see the **right** side in the screenshot
When we work with the c# SDK for azure storage we're getting the right numbers - see **left** side in the screen shot (csharp code below):

![image](https://user-images.githubusercontent.com/22839439/144747565-e4c8e6cc-ade0-49ba-a495-3e14cd3def1d.png)

```csharp
public async Task Run()
        {
            m_tracer.TraceInformation($"{nameof(StorageAccountMetricsLogger)} - Starting work.");
            CloudStorageAccount storageAccount = m_aadStorageProvider.GetStorageAccount(m_queueStorageName);
            var queueClient = storageAccount.CreateCloudQueueClient();
            var queueNames = queueClient.ListQueues();
            foreach (var cloudQueue in queueNames)
            {
                var dimension = new Dimensions();
                dimension.SetDimension("Name", cloudQueue.Name);
                var instrumentor = new Instrumentor(dimension);
                await cloudQueue.FetchAttributesAsync();
                if (!cloudQueue.ApproximateMessageCount.HasValue)
                {
                    m_tracer.TraceWarning(0, $"{nameof(StorageAccountMetricsLogger)} - Failed to retrieve message count for storage queue {cloudQueue.Name}.");
                    continue;
                }
                instrumentor.LogMetric(s_monitoringStorageQueueActiveMessageCountMetricName, cloudQueue.ApproximateMessageCount.Value);
                m_tracer.TraceInformation($"{nameof(StorageAccountMetricsLogger)} - Metrics for storage queue name \"{cloudQueue.Name}\" messages = {cloudQueue.ApproximateMessageCount}");
            }
            m_tracer.TraceInformation($"{nameof(StorageAccountMetricsLogger)} - Done.");
        }
```

### Expected Behavior

keda should report the actual # of messages in queue

### Actual Behavior

keda is reporting 0 messages in queue

### Steps to Reproduce the Problem

1. add messages to azure queue
2. query the queue with keda

### KEDA Version

2.4.0

### Kubernetes Version

1.19

### Platform

Other

### Scaler Details

Azure storage queue

**Comment by JorTurFer** [comment]
Hi @jungopro 
Could you share KEDA's logs? (from operator and metric server)

**Comment by RamCohen** [comment]
Hi @jungopro

I was unable to reproduce the issue. Note that the scaler code also peeks at the queue to try to get an accurate number in order not to use the approximation if a definite number can be obtained.
What is the size of the messages in the queue ? If they are large it may be a result of a timeout during the peek phase.

**Comment by antonio-policastro** [comment]
I've just run into the same problem, and it's a big one for my use case.
It happens when the queue messages are not deleted within seconds after being popped from the queue.

The scaler [peeks messages](https://docs.microsoft.com/en-us/rest/api/storageservices/peek-messages), and peek returns the **visibile** messages in the queue.
When a client [Gets a message](https://docs.microsoft.com/en-us/rest/api/storageservices/get-messages) from the queue, it doesn't delete it immediately: it only hides it for a configurable period of time (see: [visibility timeout](https://docs.microsoft.com/en-us/rest/api/storageservices/get-messages#remarks)) which defaults to 30 seconds.
The message must be deleted with a separate [Delete operation](https://docs.microsoft.com/en-us/rest/api/storageservices/delete-message2).

Let's say I enqueue 10 messages.
Keda peeks 10 messages and creates 10 pods.
Each pod gets a message from the queue, processes it (e.g: calls a webservice, sends an email, etc) and then deletes the message.

If the time needed to process the message is high (e.g: a few hours), Keda will peek 0 messages and will try to scale in to 0 pods.

**Proposed solution:**
The scaler should [Get Queue Metadata](https://docs.microsoft.com/en-us/rest/api/storageservices/get-queue-metadata) insteak of Peek, and then use the `x-ms-approximate-messages-count` response header to scale in/out.
`x-ms-approximate-messages-count` includes hidden messages too.

**Comment by zroubalik** [comment]
I am total Azure (Storage) noob, but in general, if it takes a few hours to process a message, then ScaledObject might not be the right option, you should try to use ScaleJob.

**Comment by JorTurFer** [comment]
Hey @antonio-policastro 
I think that [the implementation](https://github.com/kedacore/keda/blob/4e6be90bef4902f81e81af8f9ba028d9089aa7af/pkg/scalers/azure/azure_queue.go#L33) can recover the expectation of more than 32 messages.
I'm not an expert in azure sdk, but I think that we check if they are less than 32 and if not, we check the estimate amount of them so we can get more than 32

**Comment by antonio-policastro** [comment]
Oh, I see. Thanks, i completely missed that you were already using ApproximateMessagesCount _when the queue has more thank 32 messages_.
During my tests I always had less than 32 messages.

I believe that the scaler should _always_ use ApproximateMessagesCount and never Peek, because Peek can't see hidden messages.
What do you think?

From [docs](https://docs.microsoft.com/en-us/azure/storage/queues/queues-storage-monitoring-scenarios?tabs=azure-powershell#monitor-message-counts-in-each-queue):
> If you need to dynamically determine whether to adjust workloads to handle message volume, you can query approximate message count on each queue and then respond with the appropriate action. Use the [Get Queue Metadata](https://docs.microsoft.com/en-us/rest/api/storageservices/get-queue-metadata) REST operation or use any of the supported Blob storage SDKs to get the approximate message count.

**Comment by JorTurFer** [comment]
I'm not sure about it, peek returns the value with accuracy.  ApproximateMessagesCount (at least in .NET SDK) could return more messages than actual count

**Comment by RamCohen** [comment]
Right. Approximate may return >0 count when in fact there aren't any
messages at all.
This looks more and more like something that we can resolve with a scaler
parameter that will determine whether to use peek or not

**Comment by antonio-policastro** [comment]
A scaler parameter would solve my problem (and [jungopro](https://github.com/jungopro)'s too), and it wouldn't be a breaking change. Upvote!
I didn't know that ApproximateMessageCount could return a wrong (higher) number. Can you point to some documentation about it? I can't find anything.

Thanks everyone for your prompt answers.

**Comment by JorTurFer** [comment]
hey @antonio-policastro 
This is the [.NET docs](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.models.queueproperties.approximatemessagescount?view=azure-dotnet) about that method.

**Comment by wallflower762** [comment]
Did anything happen with this?

I am in exactly the same situation as [jungopro](https://github.com/jungopro) both with the scaling issue with visible messages, and the viability of scaled jobs.

Not including invisible messages doesn't seem right. If I have KEDA set to scale 5 messages per pod, and I have 5 messages in progress, it would take another 6 messages to make KEDA request a second pod. It also results in the race condition observed here were if all of the in progress messages are not completed within the cooldown time frame, KEDA will scale in while they are still processing.

Having the option to use approximate message count instead seems ideal.

On a side note: when using Azure functions on an App Service Plan, you can scale based on storage queue length. The implementation Azure has used for this is approximate message count, and does not offer any other method of scaling based on queue length.

A screenshot from the app service plan scale rules GUI:
![image](https://user-images.githubusercontent.com/81551380/184562934-543e0621-dbf4-4e6b-afd6-9a44a17f0831.png)

**Comment by wallflower762** [comment]
I am not sure if my earlier comment will trigger this issue to be reopened, so I raised a feature request as well.
