### ISSUE TITLE
KEDA scalers that use authentication require access from keda namespace

### ISSUE THREAD

**Issue by zonnie** [kedacore/keda#2445]
Hi,

So this is kind of something we are discussing in my team.
We deploy KEDA in `keda` namespace and for, i.e., MongoDB autoscaler we need to give the relevant credentials.
Also we deploy multiple MongoDBs in different namespaces.
What this means for us is that the operator in `keda` namespace essentially has credentials for MongoDBs in **all** namespaces.

We usually block all inbound communication to all `namespaces` besides very specific needs (i.e. `ingress-nginx`)

1. Are we understanding it correctly that a single `pod` in the `keda` namespace does all the auth/queries in MongoDB ?
2. Is there a way for us to mitigate the risk of having a single `pod` with all the auth data ?

We want to avoid deploying KEDA in each namespace as it's wasteful and harder to manage

Thanks

**Comment by JorTurFer** [comment]
Hi
What do you mean for mitigating the risk? It's KEDA process by itself who has the secrets, not the pod or namespace, I mean, KEDA queries them directly to k8s api or vault, so accessing to the pod is not enough to expose the secrets (they are not mount as a file nor env). 
Limiting the access to the logs could be another action, we obviously try to avoid secret exposing but maybe by error we could expose one of them in the logs, etc.

From secret management pov, KEDA supports several pod identities, in case of having a scaler that allow it, it's 100% recommendable if you use pod identity instead of secrets (mongoDB doesn't support any identity pod, but AWS/Azure yes)

And yes, you understand it correctly, they are basically 2 pods, the operator and the metric server and they do from keda namespace all the queries to all upstream everywhere (other namespaces, external services, etc)
