### ISSUE TITLE
HPA is not created for deployments with long names

### ISSUE THREAD

**Issue by bmalka** [kedacore/keda#2915]
### Report

Related to bug #704 

Error:
HPA is failing to be created: controller.scaledobject Failed to update ScaledObject with scaledObjectName label 

### Expected Behavior

HPA should be created

### Actual Behavior

HPA wasn't created

### Steps to Reproduce the Problem

1.  Add a deployment with name longer than 45 chars
2.
3.

### Logs from KEDA operator

```
1.650181258876292e+09 ERROR controller.scaledobject Failed to update ScaledObject with scaledObjectName label {"reconciler group": "keda.sh", "reconciler kind": "ScaledObject", "name": "kafka-scaledobject-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxx-xxx-xxxxxx-xxxxxxxxx", "namespace": "production-xx-xxxxxxxxxx", "error": "ScaledObject.keda.sh "kafka-scaledobject-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxx-xxx-xxxxxx-xxxxxxxxx" is invalid: metadata.labels: Invalid value: "kafka-scaledobject-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxx-xxx-xxxxxx-xxxxxxxxx": must be no more than 63 characters"}
```

### KEDA Version

2.6.1

### Kubernetes Version

1.21

### Platform

Amazon Web Services

**Comment by JorTurFer** [comment]
Hey,
I'd say that the problem is related with the ScaledObject length. Is there any option to reduce it? I have created a PR (linked to this issue) but we are discussing it there

**Comment by tomkerkhove** [comment]
From https://github.com/kedacore/keda/pull/2995: We need to have a robust solution where creating two ScaledObjects with the same name does not break the link.

Current thinking: Generate unique IDs per ScaledObject and use those instead. These unique IDs should be available to end-users (ie when doing `kubectl get scaledobject`) so that they can use them as well.

**Comment by JorTurFer** [comment]
yes, as @tomkerkhove said, we have to think it better so this fix will not be included till v2.8. Meanwhile, you could try reducing the ScaledObject name size 🙏

**Comment by zroubalik** [comment]
What we can do, is to generate some UID suffix to name like, `keda-hpa-...` in case the standard generated name would be too long. This way we would keep the original design, but also offer solution for longer names.

**Comment by JorTurFer** [comment]
Yes, but in that case we should add the current name as an annotation IMO to having a simple way to track which is what without inspecting all the SO looking for the UID

**Comment by tomkerkhove** [comment]
What if somebody changes the annotation and breaks the link?

> Current thinking: Generate unique IDs per ScaledObject and use those instead. These unique IDs should be available to end-users (ie when doing `kubectl get scaledobject`) so that they can use them as well.

I think this is a more future-proof fix long term. We can work around it so that we can fit it in the current model but that feels more like a hack to me.

**Comment by JorTurFer** [comment]
No no, I'm not saying to link them using the annotation in the HPA, I see it as a helper for human discovery, KEDA should continue using the current approach of registering it in the SO Status. I know that the HPA is something internal for KEDA, but end-users check it, so if we change the name to another one with random names, IMO we should provide a workaround to know what HPA is related with what SO without having to go SO by SO checking their status. 
But I'm doing it like a candy for users, not to use it at all in KEDA's behavior

**Comment by tomkerkhove** [comment]
I agree, good idea 👍

**Comment by dogzzdogzz** [comment]
We encounter this issue recently, too. Can we raise the severity of this issue and fix it soon? 

This issue makes KEDA not reliable because we expect the deployments with scaledobject resource in production environment are supposed to be able to autoscale but in fact, it might not because the length of the name exceeds. Now we have to sort out all deployments with name longer than 45 chars and spend extra effort to rename them and update the endpoint in their downstream service. 

Also quite difficult to restrict the length of the name of any new workloads in company.

**Comment by zroubalik** [comment]
We are limited by k8s restrictions on labels and name, though you can provide custom HPA name in the advanced config: https://keda.sh/docs/2.9/concepts/scaling-deployments/#advanced

**Comment by michaelbannister** [comment]
Hi, similar-but-different to the issues mentioned previously, I've found that an HPA can't be created if the ScaledObject's name exceeds 63 characters, because of [this code](https://github.com/kedacore/keda/blob/release/v2.11/controllers/keda/hpa.go#L98) which wants to set the HPA's label `app.kubernetes.io/part-of` with the ScaledObject's name.

Would it be more helpful for me to raise a new issue about this?
