### ISSUE TITLE
Migrate e2e test for CPU scaler to Go.

### ISSUE THREAD

**Issue by v-shenoy** [kedacore/keda#3169]
### Proposal

Relates to https://github.com/kedacore/keda/issues/2357, https://github.com/kedacore/keda/issues/2737.

**Comment by Ritikaa96** [comment]
Hi @JorTurFer  Just couldn't skip this one, I'm curious, we had a check last time for job status because sometimes jobs tend to be erroneous after they are successfully applied, or we can say the pods it will run may cause some error. if the e2e is passing on our ci/cd side for some reason now, don't we still need to check job status as a precaution for the future? 
WDYT?

**Comment by JorTurFer** [comment]
as we discussed in slack, it's not required even it's a good idea
