### ISSUE TITLE
Pod which is on old node is getting terminated while using keda autoscaling

### ISSUE THREAD

**Issue by MahajanSanjana29** [kedacore/keda#3362]
### Report

Let's say we have 2 nodes initially A,B and one service has one pod(P1) which is on node(A).We have configured keda auto-scaling for that service and then 2 more pods(p2 and p3) got scaled up.Now p2 is running on B and new node(C) got scaled up.
Now p3 got up and running on Node C.
So afterdown scale p1 and p2 got terminated and the pod(p3) which on new node(C)  is running.Ideally we want the pod which is running on old nodes should be up and running.

### Expected Behavior

After downscale we want p1 which is on node(A) or p2  which is on node(B) to be running state.

### Actual Behavior

After downscale p1 which is on node(A) and p2  which is on node(B) are getting terminated and p3 which is on new node(C) is being in running state.

### Steps to Reproduce the Problem

1.Configure keda auto-scaling for any of the service.
2. Start load testing to scale up new node and  to scale up the maximum number of pods
3.After completing load testing,observe how the pods are getting scaled down.

### Logs from KEDA operator

```
example
```

### Kubernetes Version

1.21

### Platform

Amazon Web Services

**Comment by JorTurFer** [comment]
Hey @MahajanSanjana29 
Are you using `Deployment`? I mean, KEDA doesn't manages the autoscaling itself, KEDA delegates to the HPA Controller the job and it's the HPA Controller who decides which pods should be removed (like with the normal CPU HPA).
If you want to remove the pods in the opposite order from the order they were created, I'd suggest to use `StatefulSet` (scaling with KEDA in the same way) because the StatefulSet autoscaling has de behaviour that you are looking for :)
