### ISSUE TITLE
Azure Agent offline when scale down

### ISSUE THREAD

**Issue by StManolo** [kedacore/keda#3648]
### Report

Hello,
When keda scales multiple pods, they are not always deleted in VSTS console and have gone offline.

![image](https://user-images.githubusercontent.com/38782268/188897337-cafcab8b-6e78-4e4c-8cf5-7f0c2b74bc57.png)

### Expected Behavior

All pods deleted by Keda should disappear from the VSTS console

### Actual Behavior

Sometimes, pods deleted by Keda don't disappear from the VSTS console

### Steps to Reproduce the Problem

Trigger scalling of agent vsts
wait until there is only one pod left and look in VSTS console

### KEDA Version

2.8.1

### Kubernetes Version

1.23

### Platform

Google Cloud

### Scaler Details

Azure

**Comment by JorTurFer** [comment]
Hey,
Sorry, I haven't seen this issue before :(
KEDA doesn't manage the upstreams, the only thing it does is querying them to get the metrics. Your agent docker image should unregister the agent during the stop. If you are already doing it, maybe it's because the grade period is too short and it doesn't have time to unregister itself
