### ISSUE TITLE
Keda scaler object abruptly kills the pods in middle

### ISSUE THREAD

**Issue by jakond1** [kedacore/keda#3674]
One of user  is using KEDA to scale up and down the pods according to service message count which is working as expected 

However customer pods are abruptly terminating as part of scaledown while the pod is handling application requests or processing data .this causing loss of application connection in between..

So user wants to know if there is option or possiblity so that keda waits for pod till request complete and then scale down the pod. below is the scaled object for the same. Can we use scaling jobs to accomplish the requirement.

**Comment by JorTurFer** [comment]
If you have long executions processes, I'd recommend to use ScaledJobs for it because you can guarantee that the job finishes.ç
ScaledObject delegates in the HPA Controller and KEDA doesn't have any control about which pods are killed. You could set the grace period in the deployment or intercept the stop using hooks, but I'd recommend the jobs
