### ISSUE TITLE
SealedJob image update

### ISSUE THREAD

**Issue by arkadipdigite** [kedacore/keda#3817]
I am deploying a `SealedJob` using Keda. It is working fine. But I don't know how to update the image which is running in the jobs.

I am using `Keda 2.7.1`.

My SealedJob object has `rolloutStrategy: gradual`, but to update the image I am currently removing the entire object by `kubectl delete` and redeploying it.

If anyone knows the any better command, please help.

**Comment by darkmatter18** [comment]
@JorTurFer

Hi, so the way we can update the image of a deployment using the `kubectl set image` command, that same way I wanted to update the `ScaledJob` image. 

And by using `rolloutStrategy: gradual`, I wanted to use the image for the next triggered jobs.

**Comment by JorTurFer** [comment]
oh, did you mean a single kubectl command for setting that parameter instead of applying the whole manifest?

**Comment by darkmatter18** [comment]
@JorTurFer 

Yes, just to update the image.

**Comment by JorTurFer** [comment]
> My SealedJob object has rolloutStrategy: gradual, but to update the image I am currently removing the entire object by kubectl delete and redeploying it.

You could just redeploy it doing again `kubectl apply -f MANIFEST.YAML`

**Comment by JorTurFer** [comment]
> @JorTurFer
> 
> Yes, just to update the image.

You could use `kubectl patch` to modify the images

**Comment by arkadipdigite** [comment]
@JorTurFer 

Can you give me any command?

**Comment by JorTurFer** [comment]
`kubectl patch`

**Comment by arkadipdigite** [comment]
With this command

```bash
kubectl patch ScaledJob eod-heurestics-job  -n ml-iot-camera --patch 'spec:\n jobTargetRef:\n  template:\n   spec:\n    containers:\n     - name: eod-heurestics-job\n       image: <container>'
```

I am facing this error
```bash
error: unable to parse "spec:\\n jobTargetRef:\\n  template:\\n   spec:\\n    containers:\\n     - name: eod-heurestics-job\\n       image: <container>": yaml: mapping values are not allowed in this context
```

**Comment by JorTurFer** [comment]
I have tried this and works:
`kubectl patch ScaledJob test --type='merge' --patch '{"spec": { "jobTargetRef": { "template": { "spec": { "containers": [{ "image": "nginx", "name": "test" } ] }}}}}'
`
probably you have any typo in your command
In any case, I suggest reapplying the manifest, using `kubectl apply -f manifest.yaml` you can modify the manifest and reapply it with the same command, if you have conflicts I guess that it's because you use `kubectl create` instead of `kubectl apply`, I mean, you can use `kubectl apply` always, even the resource is not created yet, it's idempotent
