### ISSUE TITLE
Add documentation for replacing existing HPA with an Scaled Object without deleting the existing resource

### ISSUE THREAD

**Issue by ivan-santos-eq** [kedacore/keda#4066]
### Use-Case

In a company where most of the services already have HPA, it would be ideal to have a backward compatible transition to ScaledObjects where it would take over the existing HPA, while the user would only need to delete the HPA yaml file (not using git ops).

**Comment by tomkerkhove** [comment]
Transferring to core repo as this might be a feature we can introduce. If not, then we should provide better docs

**Comment by JorTurFer** [comment]
@ksemele ,
Do you mean an example about how to deploy a workload with KEDA? If that's your request, there are some exmples in kedarcore org, with Azure Service Bus and also with RabbitMQ

- https://github.com/kedacore/sample-dotnet-worker-servicebus-queue
- https://github.com/kedacore/sample-go-rabbitmq

**Comment by pragmaticivan** [comment]
This feels relevant, by using `advanced.horizontalPodAutoscalerConfig.name` with the same name as the HPA, would that replace the existing resource? @JorTurFer @tomkerkhove

**Comment by JorTurFer** [comment]
Currently, there isn't any way to do it because the [validation webhook](https://keda.sh/docs/2.10/concepts/admission-webhooks/) will block the ScaledObject if it's already managed by another ScaledObject or HPA, so you can't deploy a ScaledObject for a workload already monitored by another HPA.

⚠️ **Under your own risk as an expert user:** I have tried disabling the webhooks and it works (KEDA replaces the already existing HPA, taking the control), but remember to enable again the webhooks after it because they are there to avoid problems like 2 ScaledObject monitoring the same workload (with a crazy result)

**Comment by pragmaticivan** [comment]
@JorTurFer 
Do you see a world where the validation webhook would skip that if a flag is in place and the other resource is just an HPA (without any metadata relating it to a Scaled Object) ?

Something like:

advanced.takeOverExistingHPA = true

**Comment by JorTurFer** [comment]
I think that it's something doable and could enable migration scenarios 😄 

Could you open another issue to track the new feature?

**Comment by pragmaticivan** [comment]
Yes, thx!!

**Comment by pragmaticivan** [comment]
Done: https://github.com/kedacore/keda/issues/4457
