### ISSUE TITLE
Cannot connect to service bus using azure workload identity

### ISSUE THREAD

**Issue by ilya-scale** [kedacore/keda#4219]
### Report

I have a managed identity with a federated identity that is used inside a pod via workload identity.

When I try to use the same identity, I get this error:

STS70021: No matching federated identity record found for presented assertion ... Assertion Subject: 'system:serviceaccount:keda:keda-operator'

The documentation does not say explicitly that I have to have a federated credentials with this subject. Is there a bug in implementation or maybe in the documentation?

Am I supposed to create federated credentials both for my pod and for keda?

### Expected Behavior

Either the documentation should mention this, or it should work with pod subject.

### Actual Behavior

Error: AADSTS70021: No matching federated identity record found for presented assertion

### Steps to Reproduce the Problem

1. Create a pod that connects to service bus via azure workload identity using federated credentials
2. Add keda trigger for service bus that uses the same managed identity
3. The error happens

### Logs from KEDA operator

```
2023-02-09T15:12:10Z    ERROR   scalers_cache   error getting scale decision    {"scaledobject.Name": "myobject", "scaledObject.Namespace": "mynamespace", "scaleTarget.Name": "myname", "error": "ChainedTokenCredential authentication failed\nPOST https://login.microsoftonline.com/mytenantid/oauth2/v2.0/token\n--------------------------------------------------------------------------------\nRESPONSE 400 Bad Request\n--------------------------------------------------------------------------------\n{\n  \"error\": \"invalid_request\",\n  \"error_description\": \"AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://northeurope.oic.prod-aks.azure.com/someid/'. Assertion Subject: 'system:serviceaccount:keda:keda-operator'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\\r\\nTrace ID: ff72f2ba-ccad-4d71-b1bf-8cefd41f4600\\r\\nCorrelation ID: 4cca812e-6de5-4bcc-bd22-a001682427a2\\r\\nTimestamp: 2023-02-09 15:12:10Z\",\n  \"error_codes\": [\n    70021\n  ],\n  \"timestamp\": \"2023-02-09 15:12:10Z\",\n  \"trace_id\": \"ff72f2ba-ccad-4d71-b1bf-8cefd41f4600\",\n  \"correlation_id\": \"4cca812e-6de5-4bcc-bd22-a001682427a2\",\n  \"error_uri\": \"https://login.microsoftonline.com/error?code=70021\"\n}\n--------------------------------------------------------------------------------\n"}
```

### KEDA Version

2.9.3

### Kubernetes Version

1.24

### Platform

Microsoft Azure

### Scaler Details

Azure Service Bus

**Comment by JorTurFer** [comment]
Hey,
We don't explain explicitly how to create the required federation because it's not KEDA scope, sorry, it could be an improvement for the docs (are you willing to contribute with that?)
Answering your question: yes, KEDA needs its own federation because due to how worklaod identity federation works, it relies on the service account subject and KEDA has its own service account (different from your application service account).
I guess that you already know how to create/federate an identity because you have done it for the app, but just in case we have an example https://github.com/kedacore/sample-dotnet-worker-servicebus-queue/blob/main/workload-identity.md

**Comment by ilya-scale** [comment]
Thank you for the answer! It is not KEDA responsibility, I agree, but it should perhaps just mention that a separate federated credentials are required and provide the subject format that should be added.

This was not immediately obvious and just a mention of that would help, even without details on how exactly this should be created.

**Comment by JorTurFer** [comment]
> This was not immediately obvious and just a mention of that would help, even without details on how exactly this should be created.

Yes, you are totally right (that's why I asked if you are willing to contribute with the docs improvement :) )

**Comment by JorTurFer** [comment]
Maybe a note in the [authentication provider doc](https://keda.sh/docs/2.9/authentication-providers/azure-ad-workload-identity/) is enough for helping

**Comment by ilya-scale** [comment]
I will see what I can do :) Can you point me maybe to some of the details on how that works in code, e.g. it does not fully rely on workload identity webhook (e.g. the operator does not use the AZURE_CLIENT_ID that the workload identity injects)

**Comment by JorTurFer** [comment]
No no, it relies totally on `AZURE_CLIENT_ID`. I mean, the field `identityId` is for using other clientId different from `AZURE_CLIENT_ID`. if you don't provide any clientId (which is the most common scenario), the clientId used is `AZURE_CLIENT_ID`.
The option to provide other clientId is to not stack a lot of permissions in the same msi thanks to use multiple msi (but all of them should be federated with KEDA service account)

**Comment by ilya-scale** [comment]
What I meant is that workload identity webhook injects (or can inject) the AZURE_CLIENT_ID from the manifest. But since keda operator supports logging in as multiple identities from "identityId" definition as you point out, it does something special to achieve this I suppose, so I was thinking it might be a good idea to add this to docs as wel, but I do not fully understand what is going on :)

**Comment by JorTurFer** [comment]
The only requirement for using multiple identities is that all the identities need to have a federation with KEDA service account. From the code pov, KEDA reads the value of AZURE_CLIENT_ID and the value of the clientID in the trigger authentication. If the trigger authentication doesn't have any client ID, AZURE_CLIENT_ID is used, if not, the trigger authentication clientID is used.
In any case, as I said, all the identities need to have a federation with KEDA service account and also, KEDA needs to have a "regular" identity. I mean, you cannot just use a clientID provided by trigger authentication, you need to configure KEDA with an identity (because the "regular" identity in the service account will trigger the mutation by the workload identity webhook). If you don't provide any identity as default for KEDA, you cannot use only the trigger authentication clientId because the needed resources won't be there. This feature is for overriding the process, not to replace it

**Comment by ilya-scale** [comment]
Great, thanks for the explanation, I can try to add a small PR to docs

**Comment by ilya-scale** [comment]
I have opened a PR with some small changes here: https://github.com/kedacore/keda-docs/pull/1069

**Comment by JorTurFer** [comment]
> I have opened a PR with some small changes here: [kedacore/keda-docs#1069](https://github.com/kedacore/keda-docs/pull/1069)

Thanks! I think someone will review it soon
