### ISSUE TITLE
Ignore failed triggers

### ISSUE THREAD

**Issue by omerlh** [kedacore/keda#4533]
### Proposal

When a ScaledObject has more than one trigger, if one of the triggers is in failure state exclude it from the HPA and keep the HPA healthy. For example, if you define Prometheus, CPU and Memory triggers, and for some reason the Prometheus trigger is not able to provide the metric value due to any kind of error - use only the CPU and Memory triggers.

### Use-Case

We have cases where we have multiple triggers, one of them is Prometheus. We had incident this week with Prometheus, which cause all ScaledObject to stop scaling up / down the services. This is not ideal, and we would like a way to safely ignore this error.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by derekperkins** [comment]
This would be a great addition

**Comment by zroubalik** [comment]
This sounds reasonable, I can see a new property next to `type`,`metadata` etc in the triggers section: https://keda.sh/docs/2.10/concepts/scaling-deployments/#triggers

**Comment by gustavomassa** [comment]
KEDA already handle multiple scalers, but it's missing a LOG configuration so we can customize/ignore failed triggers as needed. This is the same case mentioned in this issue, imagine we have CPU/Memory/Prometheus scalers, but Prometheus scaler fails because Prometheus is offline/unstable for a period of time, keda-operator and keda-metrics-server will keep logging all errors related to prometheus metrics, now image we have 100 services that uses prometheus scalers, it's a lot of errors logs generated by KEDA.

Does KEDA have any way to ignore/customize failed metrics logs?  Or set a maximum log error threshold by time period?

@zroubalik What about adding a new trigger property about how KEDA should handle error logs for failed triggers?
