### ISSUE TITLE
Prisma Cloud's scan reported Private Key found in keda-metrics-apiserver

### ISSUE THREAD

**Issue by edwardccg** [kedacore/keda#4869]
### Report

Our cluster's integrated with Prisma Defender, it reported that Private Key was found in keda-metrics-apiserver:2.9.2.

**Cause**
Found: /apiserver.local.config/certificates/apiserver.key

### Expected Behavior

There's should be no private key stored inside an image.

### Actual Behavior

Private key is stored in image

### Steps to Reproduce the Problem

Private key was detected in /apiserver.local.config/certificates/apiserver.key

### Logs from KEDA operator

N/A

### KEDA Version

2.9.2

### Kubernetes Version

None

### Platform

Microsoft Azure

### Anything else?

Please advise if this private key is required for the keda-metrics-apiserver to be function. If not required, we should remediate and externalize the keys from image. If required, we need some inputs to document why the key is required. Thank you.

**Comment by JorTurFer** [comment]
Hi,
That key isn't stored in the image, it's generated on the fly by the metrics server during the startup if you don't provide it.
How to provide your own certificate is explained here: https://keda.sh/docs/2.11/faq/

![image](https://github.com/kedacore/keda/assets/36899226/99cb94e1-e671-4907-81cb-6b7d5e89fc6a)

This certificate has been removed in KEDA v2.10 in favor of external certificates (managed by KEDA as minimum, using an external tool like cert-manager as recommended)
You can find how to use your own certificates in KEDA > v2.10 [here](https://keda.sh/docs/2.11/operate/security/#use-your-own-tls-certificates) and also a blog-post with an example for cert-manager [here](https://keda.sh/blog/2023-05-02-certificate-improvements/)

I close this issue as solved because the file isn't used anymore, but you can reopen it if you think that there is still something that needs to be fixed 😄

**Comment by edwardccg** [comment]
Thank you for the information, we do use cert manager, I will have a look on v2.10 and implement that.

**Comment by JorTurFer** [comment]
Just upgrading KEDA, the issue should be solved with the certificate managed by KEDA operator through k8s secrets

**Comment by edwardccg** [comment]
Thanks! I have upgraded to current latest version of 2.11.2 and Prisma Cloud is all green for the container running in keda namespaces.
