### ISSUE TITLE
Add support for scaling by Google Pub/Sub subscription publish rate

### ISSUE THREAD

**Issue by mbrancato** [kedacore/keda#5070]
### Proposal

Scaling by unacknowledged messages and oldest message are good, reactive scaling metrics. If a queue is behind, both of these are good for responding to how much is currently in the queue. They are, however, reactive and likely can lead to constant scaling up and down to keep up with consistent message volumes.

It would be nice if there was a trigger based on the rate of incoming messages (`pubsub.googleapis.com/topic/message_sizes`) to keep up with current rate, and use a reactive metric like unacknowledged messages to scale up when things get behind.

### Scaler Source

Google Pub/Sub incoming messages 

### Scaling Mechanics

Scale based on metric

### Authentication Source

GCP

**Comment by JorTurFer** [comment]
Hello!
It's a nice idea, but I think we can just add it as another flavor of the current scaler. Does GCP expose the publishing rate metric?
BTW, are you willing to contribute with the feature?

**Comment by kevinmingtarja** [comment]
Hey, I'm interested in taking on this feature!

**Comment by kevinmingtarja** [comment]
I see that there's already `pkg/scalers/gcp_pubsub_scaler.go` for Google Pub/Sub, so I'm guessing this should be a good place to start, along with other scalers in this package.

But please let me know if you have any additional pointer, thank you!

**Comment by zroubalik** [comment]
Thanks @kevinmingtarja, yeah, that is a good starting point. [Here](https://github.com/kedacore/keda/blob/main/CREATE-NEW-SCALER.md) are docs for contributing a new scaler, you might find something valuable there.

**Comment by kevinmingtarja** [comment]
Got it, thanks for the pointers! I'll get started soon.

**Comment by kevinmingtarja** [comment]
Hi @zroubalik @JorTurFer, I did a bit of reading and have a question regarding how we should approach this.

Right now for the [GCP Pub/Sub scaler](https://github.com/kedacore/keda/blob/main/pkg/scalers/gcp_pubsub_scaler.go), the level of granularity is `subscriptions`, so as part of the metadata users supply `subscriptionName` and `mode` (which can be any metrics that starts with `subscription/`) as inputs. 

But the proposal here is to use the metric [topic/message_sizes](https://cloud.google.com/monitoring/api/metrics_gcp#pubsub/topic/message_sizes), which is a different level of granularity than `subscription/`, and thus not supported right now. The relationship between the two is that a topic can have multiple subscriptions, but a given subscription belongs to a single topic.

With this in mind, I think there are two options at least:

1. Extend the existing scaler. Perhaps we can have a new input `topicName`, and make one of `subscriptionName | topicName` required. Based on which of the two has a non nil value, we're able to figure out whether the `mode` will be a `subscription` or a `topic` metric, so we can prefix the `mode` accordingly when looking up the metric via the GCP API.
2. Create a new scaler, so we have one scaler working at the level of `subscriptions` (the existing one), and a new one for `topics`.

I'm kind of leaning towards option (1), since the API change is very limited and non-breaking, so by default it's backwards compatible as well. But I wanted to get a second opinion before starting to code. Thank you!

**Comment by JorTurFer** [comment]
> I'm kind of leaning towards option (1), since the API change is very limited and non-breaking, so by default it's backwards compatible as well. But I wanted to get a second opinion before starting to code. Thank you!

I also think that the option 1 is the best if it's not a breaking change

**Comment by kevinmingtarja** [comment]
Got it, thanks for the input Jorge

**Comment by zroubalik** [comment]
I agree with that, thanks for the investigation.

**Comment by kevinmingtarja** [comment]
After starting to code, I think the current code assumes that the metric/mode is a single value, and doesn't handle the case if it's a distribution, like for [topic/message_sizes](https://cloud.google.com/monitoring/api/metrics_gcp#pubsub/topic/message_sizes).

The main difference I can see is that for distribution, we need to specify an aggregation (example below). So I'll try to address this as well in my changes.

<img width="866" alt="Screen Shot 2023-11-26 at 03 54 49" src="https://github.com/kedacore/keda/assets/69668484/199c71dd-f479-4a2d-99ec-8c40a1bb2876">

**Comment by kevinmingtarja** [comment]
There's only a handful of metrics that is of type distribution, in which we need to aggregate the data:
1. subscription/ack_latencies
2. subscription/mod_ack_latencies
3. subscription/push_request_latencies
4. topic/message_sizes
5. topic/schema_validation_latencies
6. topic/send_request_latencies

For reference, the [GCP Stackdriver scaler](https://keda.sh/docs/2.12/scalers/gcp-stackdriver/) exposes `alignmentPeriodSeconds`, `alignmentAligner`, and `alignmentReducer` field as inputs for handling aggregation.

For our case, I'm proposing to hard-code `alignmentPeriodSeconds=60`, and `alignmentAligner="delta"`, because all six of those metrics are of type `DELTA` (there's three types, `DELTA`, `GAUGE`, and `CUMULATIVE`). And to make the API simpler, we only expose the `reducer` to the user, which are functions like sum, mean, p99, etc.

**Comment by kevinmingtarja** [comment]
Hi @mbrancato, just a heads up, once the PR for this gets in on the next release, you will be able to do what you proposed with the following params with the GCP PubSub scaler!

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
...
spec:
  ...
  triggers:
  - type: gcp-pubsub
    metadata:
      mode: "MessageSizes"
      aggregation: "count"
      topicName: "mytopic"
      ...
```
