### ISSUE TITLE
remove the requirement to specify a fully qualified hostnames

### ISSUE THREAD

**Issue by Loki-Afro** [kedacore/keda#5442]
### Proposal

remove the requirement to specify a fully qualified hostnames like  `postgres-svc.namespace.cluster.local`
make it optional, so that `postgres-svc` does work as well, i assume the operator has the information for what namespaces it does certain action

### Use-Case

in our dev instance we can spawn namespaces which share the same secrets as a base

adding the secret `AMQP_URL=bla@blub:rabbitmq-svc` is never fully qualified because multiple namespaces end up having an identical env var, although in different k8s secrets

### Is this a feature you are interested in implementing yourself?

Maybe

### Anything else?

i have seen this or similar issues in the past, unfortunately there is not really a work around for us

**Comment by JorTurFer** [comment]
Hello,
Sadly this is more complicated that it looks :( The full qualified hostname isn't an empty requirement, the problem here is that KEDA does the requests from where it's, basically, from `keda` namespace (as default). If you don't provide the namespace of the target service, KEDA will try to call inside its own namespace, failing the request. We could append the namespace at the end, but it won't work because if you are calling outside the cluster, the namespace doesn't make sense.
We could also include a parameter for that, but IDK if we'd be coupling the trigger input to a specific use case.. 🤔 
@tomkerkhove @zroubalik ?

**Comment by zroubalik** [comment]
> Hello, Sadly this is more complicated that it looks :( The full qualified hostname isn't an empty requirement, the problem here is that KEDA does the requests from where it's, basically, from `keda` namespace (as default). If you don't provide the namespace of the target service, KEDA will try to call inside its own namespace, failing the request. We could append the namespace at the end, but it won't work because if you are calling outside the cluster, the namespace doesn't make sense. We could also include a parameter for that, but IDK if we'd be coupling the trigger input to a specific use case.. 🤔 @tomkerkhove @zroubalik ?

Agree, I wouldn't introduce a new complicated setting for this.
