### ISSUE TITLE
Add support for additional SQS metrics to trigger scaling based on throughput rather than queue size

### ISSUE THREAD

**Issue by jingo64** [kedacore/keda#5488]
### Proposal

At present, we can control SQS scaling on queueLength, which includes items in the queue as well as optionally in flight/delayed messages. This generally works great, but there are some scenarios where it'd be helpful to get a sense of the current throughput of the application in order to trigger scaling pre-emptively, i.e. before waiting for the queue size to keep growing. 

### Use-Case

We have a SQS queue consumer which generally processes a message in under a second, but every now and again will take up to 2-3 minutes. The queue has around 10-20 messages per minute added. We don't especially want to scale up aggressively on queue size as 9 times out of 10 that'll be overkill and by the time the new instance is running, the queue will likely be empty anyway. Ideally, we'd be able to monitor the NumberOfMessagesDeleted attribute on SQS, and if we saw this dropped before a certain amount, it'd trigger the scaling to occur. 

There are other proxies for throughput we could also look at depending on peoples preferences, such as AgeOfOldestMessage 

### Is this a feature you are interested in implementing yourself?

Yes

### Anything else?

I'd be happy to actually do this work, just want to check it'd be accepted before I get started!

**Comment by JorTurFer** [comment]
Hi @jingo64 
you request is totally legit, my only afraid is how we can implement this. Does SQS API support recovering that info something "in one shoot"? We try to avoid storing scaling data between iterations. For example, the approach of monitoring `NumberOfMessagesDeleted` seems that requires storing and evaluating the value over the time as part of the scaler and based on it, generate a (number) result. (or maybe no and it'd be nice) 

We try to avoid these types of state, which require a local evaluation of the metric in KEDA. We do this because scalers are ephemeral and can be recreated but also can be queried multiple types by different sources, making hard to manage this local evaluations over the time. We could simplify the paragraph as: If we need to keep the metric stored in the scaler as an "in scaler cache" to evaluate the changes during the time, we shouldn't do it.

I'm interested in `AgeOfOldestMessage`, how would you support this?

**Comment by jingo64** [comment]
Thanks for the feedback @JorTurFer ! I understand your point around introducing state into the scalers - I think AgeOfOldestMessage is probably the way to go. Digging into the docs a little, I realize that this is actually a Cloudwatch attribute vs an SQS one, and I'm actually able to query on it via the existing Cloudwatch scaler, so I'll likely go down that route as I don't think it requires any changes to KEDA. I appreciate you taking the time to respond!

**Comment by JorTurFer** [comment]
you're welcome! happy to help
