### ISSUE TITLE
Keda with Prometheus Metrics not working Properly.

### ISSUE THREAD

**Issue by KillDroner** [kedacore/keda#5489]
### Report

Whenever we try to use prometheus metrics which calculate and provide output using arithmetic operations the query is unable to process it. 
which provide incorrect output. 

Example Query Used (max(container_memory_working_set_bytes{namespace="ns", pod="pod-1"}) by (pod)) / (1024 * 1024)

### Expected Behavior

Used Memory like : 2300

### Actual Behavior

random value in millions like 986m/9604m

### Steps to Reproduce the Problem

1. Use prometheus as metrics provider
2. use above mentioned query.

### KEDA Version

2.12.0

### Kubernetes Version

1.26

### Platform

Microsoft Azure

**Comment by JorTurFer** [comment]
I think that this link will help you to understand the behaviour: https://github.com/kedacore/keda/discussions/3299#discussioncomment-3046406

**Comment by KillDroner** [comment]
I want to understand if that's the format like if i get 500MB between 3 instances as 166666m then how am I supposed to use this value to scale at a threshold of 50% when my limit is 1GB for 1 pod.

**Comment by JorTurFer** [comment]
> how am I supposed to use this value to scale at a threshold of 50% when my limit is 1GB for 1 pod.

Actually, you can't do literally that but that not something that KEDA can manage because it's related with metric types. The percentage is `Utilization` metric type, and that's reserved for metrics endpoint (`metrics.k8s.io`) and KEDA uses external endpoint (`external.metrics.k8s.io`). 
What you can do in this case, if setting the target value calculated by yourself. If you have 1Gi set for the limit, and you want to scale at 50%, your target is 512Mi. Assuming that your query is adjusting the unit (it is indeed), you want to have 512Mi in average, so you should use `AverageValue` metric type (it's the default type, so you can just not set it) and a target value of 512 (without the Mi).
