### ISSUE TITLE
SQS scaler processes float target queue length in a weird way, e.g. 6.5 would result in 5 on hpa object

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [kedacore/keda#5497]
### Report

SQS scaler doesn't seem to work well with float queueLength. The documentation doesn't say it has to be integer though. A specific bug is that setting 6.5 as target queue length on KEDA scaled object resulted in a target value 5 set on the underlying HPA object (not sure how it selected that). Float values are supported for other scalers like Cloudwatch and would help here a lot too, since the system seems quite sensitive to the target value and even 0.5 difference can make replicas flap.

### Expected Behavior

The value 6.5 is set on HPA

### Actual Behavior

The value 5 is set on HPA

### Steps to Reproduce the Problem

1. Create/pick a setup with SQS-queue-based scaler.
2. Set the target queueLength to a float value.
3. Observe the incorrect value set on the HPA object.

### KEDA Version

None

### Kubernetes Version

1.24

### Platform

Amazon Web Services

### Scaler Details

SQS

### Anything else?

I couldn't find a version of KEDA. Please, let me know if the bug was already fixed in some versions.

**Comment by JorTurFer** [comment]
Hello,
That behaviour (defaulting to 5) is done because of this code:
https://github.com/kedacore/keda/blob/cdbcb9fe7e77aa4b35624ae9813b00b2c2200d70/pkg/scalers/aws_sqs_queue_scaler.go#L95-L103

Basically, you should see an error in the logs saying that.

About supporting float numbers, SQS doesn't support float numbers, all the scalers where float are supported say it explicitly. 
Should it support float numbers? Honestly IDK, SQS queues can't have float messages as message count is implicitly an integer (and that's why SQS scaler doesn't support it now), but once you have more than 1 instance, the average value is float, so maybe it makes sense... 🤷 

Are you willing to open a PR adding support?

**Comment by andrii-korotkov-verkada** [comment]
Thanks for the explanation! I'll figure out the logistics and try to work on a PR.
