### ISSUE TITLE
Support scaling of  PodDisruptionBudget to allow scale deployment to 0 in certain time windows

### ISSUE THREAD

**Issue by ecerulm** [kedacore/keda#5583]
### Proposal

Allow a ScaledObject to manage a PodDisruptionBudget natively, so it can manipulate the `minAvailable` to 0 in certain time windows. 

### Use-Case

The scenario is the following
* Deployment with 2 replicas and PodDisruptionBudget minAvailable 1 , that run on expensive hardware (gpu) on EC2. The nodes for this workload are dynamically provisioned by Karpenter
* This workload only need to run during work hours / office hours (9am-5pm) 
* After office hours I want to scale the Deployment to 0 so that Karpenter will release / decomission the ec2 instances.

Right now I can't implement the scenario above because although I have a KEDA Cron Scaler to scale the deployment to 0 after 5pm  the PodDisruptionBudget conflicts with it. (or so it seems)

The PodDisruptionBudget during office hours help to keep the workload available during deployment restarts (which happens when the developer release a new version , quite often) and in other scenarios like karpenter node consolidation.  But I don't need the PodDisruptionBudget outside office hours. 

### Is this a feature you are interested in implementing yourself?

Maybe

### Anything else?

I will also welcome any suggestion on alternative approaches to the problem

**Comment by JorTurFer** [comment]
Hello,
KEDA doesn't respect PDB and it doesn't have to respect it as the PDB is for draining operations. I mean, Karpenter has to respect the PDB when it drains the node, but KEDA can (and it does) scale to 0 the workload although the PDB says no.

I guess that the issue here is more related with [this one](https://github.com/kedacore/keda/issues/5586) that with the PDB itself.

Finally, KEDA is focus just on autoscaling and although we could modify other resources like the PDB, that is related with management and that's outside KEDA's scope. 

I close this issue in favor of https://github.com/kedacore/keda/issues/5586 because it will solve your current issue without modifying the PDB
