### ISSUE TITLE
Keda 2.14 Prometheus Scaler Divides by Number of replicas of pod

### ISSUE THREAD

**Issue by doverk96** [kedacore/keda#5781]
### Report

I am using Keda 2.14, externally hosted Prometheus for triggering the deployment running in EKS.
For every query provided, it always divides the value by the number of replicas.
Example: - count(container_cpu_cfs_throttled_periods_total{cluster="sample-prod", container=~"sample-web.*", namespace=~"prod"}) by (container)
This gives 4 in output, whereas if i run : - kubectl describe hpa sample-consumer -n qa, over there it displays value as 
Metrics:                                   ( current / target )
  "s0-prometheus" (target average value):  1334m / 21
I have 3 pods running of sample-consumer in my EKS, and therefore I can see it is dividing 4 by 3 to get 1334m as value.

### Expected Behavior

I was not expecting this inherent division by the number of replicas

### Actual Behavior

It do inherent division by the number of replicas

### Steps to Reproduce the Problem

1. Just use the query and see it divides the value by the number of replicas.
2.
3.

### Logs from KEDA operator

```
example
```

### KEDA Version

2.14.0

### Kubernetes Version

1.28

### Platform

Amazon Web Services

### Scaler Details

Prometheus

**Comment by JorTurFer** [comment]
Hello,
[It's the expected behavior for `AverageValue` metrics. You can change the metric type to `Value` to not have the average](https://keda.sh/docs/2.14/concepts/scaling-deployments/):
![image](https://github.com/kedacore/keda/assets/36899226/69c9de1a-d32f-4cf6-8e6d-c5eaa88aeee5)

To change the metric type, you just need to add `metricType: Value` in your trigger at the same level of type or metadata.
```yaml
triggers:
- type: prometheus
  metricType: Value
  metadata:
    # Required fields:
```
You can get more information about how the HPA formula is calculated here: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details

**Comment by doverk96** [comment]
Thanks

**Comment by frankjkelly** [comment]
Can this be made clearer in the documentation? 
https://keda.sh/docs/2.14/scalers/prometheus/
The example query in the documentation ` sum(rate(http_requests_total{deployment="my-deployment"}[2m]))` doesn't immediately jump out as something that should be (necessarily) averaged by pod.

As someone who historically used the CPU and Pulsar scalers this was a surprise.
For example the Pulsar scaler uses the term `Average target value to trigger scaling action` which is at least suggestive that it is being averaged (across something - although I assumed it was averaged over time, not over replicas)
https://keda.sh/docs/2.14/scalers/pulsar/
