### ISSUE TITLE
Automate update of KEDA version in the code and yaml files during each release

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#580]
## Expected Behavior
We should update a version in https://github.com/kedacore/keda/blob/master/version/version.go during each release. It is set to `1.0.0` currently, which is wrong. This value is printed in logs during the operator startup/run.
Same for the versions in the yaml files under `deploy` directory

This should be automated

## Actual Behavior
Not updated

**Comment by tomkerkhove** [comment]
That would be a new first step in https://github.com/kedacore/keda/blob/master/RELEASE-PROCESS.MD, is that right?

**Comment by zroubalik** [comment]
Yes, but I'd like to see it automated. I am not that much familiar with GitHub workflows, so not sure if that's possible. But it is a matter of very simple bash script and regex.

**Comment by zroubalik** [comment]
@ahmelsayed might know it better

**Comment by Cottonglow** [comment]
The `Makefile` in #596 will replace the version in `version.go` but the PR also introduces more files that need to be substituted.

The deploy yaml files will include a version label which currently would need to be updated manually before each release.

I have found a few ways of getting this to potentially work - although unsure whether they are too hacky:
1. Run a script to `sed` the version before creating a release
1. Update the `Makefile` to `sed` the yaml files and output the new files into a `build/deploy` folder 

The 2nd one would mean people need to go into the `build/deploy` directory to get the new scripts instead of the `deploy` directory currently.
Unless we have a `template/deploy` folder with the yaml files, copy those files to the `deploy` folder (to prevent updating files in 2 places) and do the variable substitution with `sed`.

**Comment by zroubalik** [comment]
@Cottonglow I think that a new target, like `make release` or `make prepare-release` or something like that would be great.

It would change the versions in `version.go` and yaml files (both the `app.kubernetes.io/version:` and image reference). So then it could be the first step in the release process.

**Comment by Cottonglow** [comment]
I've created the above PR which contains a new target `release`. I gave it a dry run on my side and it seems to work. Would be happy for someone else to test it as well just in case.
