### ISSUE TITLE
Configuration security rule violation , ensure service account tokens are only mounted where necessary

### ISSUE THREAD

**Issue by tsivachi** [kedacore/keda#5900]
KEDA operator should look for deploying the component with automountServiceAccountToken=false to comply with best practices around mounting service account tokens.

It seems to be that other OSS components like certmanager are able to implement a token rotation mechanism periodically and avoid mounting a static token as per this link [here](https://cert-manager.io/docs/installation/best-practice/#restrict-auto-mount-of-service-account-tokens) ?

_Originally posted by @tsivachi in https://github.com/kedacore/keda/issues/1934#issuecomment-2179295338_

**Comment by JorTurFer** [comment]
Hello
Sorry because I missed this issue 😢 
This is already supported using helm chart:
https://github.com/kedacore/charts/blob/12433cf661790abe0425f66cd4bd21e73741c010/keda/values.yaml#L289-L316

As default, we prefer to use `automountServiceAccountToken` as it's the easiest way, and it's safe with default KEDA installation (with a single container) but you can set it to false and mount the service account by yourself
