### ISSUE TITLE
Updating deployment environment variables doesn't update the kafka scaler

### ISSUE THREAD

**Issue by akuson94** [kedacore/keda#5915]
### Report

I'm using the kafka scaler with bootstrap server, consumer group and topics pulled from the deployment environment variables. 

### Expected Behavior

Updating the configmap and restarting the deployment doesn't update these values on the scaledobject

### Actual Behavior

The scaledobject should get updated.

### Steps to Reproduce the Problem

1. Create a kafka scaledobject with bootstrap server, consumer group and topics pulled from the deployment environment variables. 
2. Update the environment variables on the deployment and restart the deployment
3. Scaler is still using old values

### Logs from KEDA operator

```
example
```

### KEDA Version

None

### Kubernetes Version

None

### Platform

None

**Comment by JorTurFer** [comment]
Hello!
This is the expected behavior, KEDA only recreates the scalers when there are failures so if the old connection info is still valid, KEDA will still use it. To flush the scaler you can update the ScaledObject (e.g:  updating the target value or so) or restart KEDA.
For the moment, this is the desired behavior so I'll close the issue.
