### ISSUE TITLE
Deployment does not scale down once the state changes from Active to Inactive if MinReplicaCount is set

### ISSUE THREAD

**Issue by ckuduvalli** [kedacore/keda#804]
## Expected Behavior
Deployments should scale down to minReplicaCount once the scaler becomes inactive. However, this behavior is working as expected when minReplicaCount is 0 or not set. But if minReplicaCount is set to any other value than 0, the deployment stays at the scaled up value even after turning Inactive from Active. The code line comment says HPA will scale down for such use cases other from scale down to zero. I do not understand how is scaledown to zero different from a minReplicaCount > 0

## Actual Behavior
Deployment should scale down to actual minReplicaCount if its set

## Steps to Reproduce the Problem

  1. Write a simple time based scaler which is active only for a few minutes.
  2. The scaler scales up to a certain value depending on the GetMetrics implementation.
  3. But once scaler becomes inactive, the scaler does not scale down to minReplicaCount

## Specifications

  - **KEDA Version:** 1.4.1
  - **Platform & Version:** Linux Debian 9
  - **Kubernetes Version:** 1.17
  - **Scaler(s):** Any scaler

**Comment by zroubalik** [comment]
Scaling 1 <-> N is handled by HPA, it has it's own [cooldown policy](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-cooldown-delay) (cluster wide).

Scaling 0 <-> 1 is handled by KEDA, that's why you see the difference.


FYI, there are new options to define HPA scaling capabilities, introduced in kubernetes 1.18. We are planning to bring this in KEDA v2.
https://github.com/kedacore/keda/issues/802

**Comment by ckuduvalli** [comment]
Any harm in KEDA handling 1 <-> N use case? I made a simple code change for this.

**Comment by tomkerkhove** [comment]
We are not doing the 1 <-> N scaling as it's baked into Kubernetes so we feel that is a good boundary so that we don't reinvent the wheel, hope that makes sense?

Or did I misinterpret your question?

**Comment by ckuduvalli** [comment]
Thanks @tomkerkhove and @zroubalik for helping out. I got the point.
