### ISSUE TITLE
Script to convert existing ScaledObjects from v1 to v2

### ISSUE THREAD

**Issue by zroubalik** [kedacore/keda#946]
We should release a script that will convert existing `ScaledObjects` from v1 to v2, and handle the conversion from `v1.ScaledObject.JobType` to `v2.ScaledJob`

**Usecase 1**
The Migration scenario would be:
1. KEDA v1 is running in the cluster
2. User installs v2 CRDs
3. Run the script to do the conversion from v1 to v2, this would create `v2.ScaledObjects` next to `v1`
4. Install KEDA v2
5. Delete `v1.ScaledObjects`
6. Uninstall KEDA v1

**Usecase 2**
The script should be able to convert ScaledObjects defined in yamls in a particular directory

**Comment by zroubalik** [comment]
@tbickford FYI

**Comment by tomkerkhove** [comment]
Great idea!

**Comment by tomkerkhove** [comment]
Yesterday during standup @tbickford mentioned he wanted to pick this up

**Comment by tbickford** [comment]
I was looking into what the conversion process would like for deployments only and was hoping for some feedback. Assuming that the v2 crds are installed these commands should convert the CR's:
```
kubectl get triggerauthentications.keda.k8s.io -A -o json --export \
    | jq '.items[].apiVersion = "keda.sh/v1alpha1"' \
    | kubectl apply -f -

kubectl get scaledobjects.keda.k8s.io -A -o json --export \
    | jq '.items[].apiVersion = "keda.sh/v1alpha1"' \
    | jq 'del(.items[].metadata.finalizers)' \
    | jq '.items[] | .spec.scaleTargetRef = {"name": .spec.scaleTargetRef.deploymentName}' \
    | kubectl apply -f -
```
Before the v2 keda operator is installed or started the previously KEDA-provisioned HPA's need deleted:

`kubectl delete hpa -A -l app.kubernetes.io/managed-by=keda-operator`

Once the v2 operator is up and running the new HPA's should be provisioned.

For cleanup of the v1 Custom Resources:
```
kubectl get scaledobjects.keda.k8s.io -A -o json \
    | jq '.items[].metadata.finalizers = []' \
    | kubectl apply -f -

kubectl delete scaledobjects.keda.k8s.io --all
kubectl delete triggerauthentications.keda.k8s.io --all
kubectl delete crd scaledobjects.keda.k8s.io 
kubectl delete crd triggerauthentications.keda.k8s.io
```

Thoughts?

**Comment by zroubalik** [comment]
Looking good. What if user would like to convert yaml files, no resources in k8s?
We should take into an account the last big changes that we hopefuly would do for v2.0 - as described in this comment https://github.com/kedacore/keda/issues/753#issuecomment-656224125, renaming confusing properties (ie. where they use direct value, when reference).

**Comment by tbickford** [comment]
Yaml (files) are interesting. The intent of what I was looking to address here was only for the custom resources existing in the cluster and the applications/deployment that are preserved as files would need to be altered out of band. The reason for this is that they are not necessarily straight yaml (Helm templates for example).

Are these scaler property changes going to happen in v2 (interestingly enough the issue referenced was the same problem I initially faced)? Is there a document/list of all the property changes that will be occurring?

**Comment by zroubalik** [comment]
@tomkerkhove collected a doc in that issue (https://docs.google.com/document/d/1DWjG2GfhxO8nWrLciTLtHW2y6YDkj2CF7n3abj4-pmE/edit)

Basically we would like to through scalers' metadata fields and change those ambiguous. Eg. https://github.com/kedacore/keda/issues/905. So if there's such field, for example `connection` which expects value in some reference, rename this property to `connectionRef` or `connectionEnv` and introduce `connection` property for this scaler, where user can specify the value directly.

Have I specified this correctly @tomkerkhove @ahmelsayed @jeffhollan ?

Unfortunately we are still looking for volunteers to implement this 😄

**Comment by AshutoshNirkhe** [comment]
So following steps mentioned in https://github.com/kedacore/keda/issues/946#issuecomment-675803662, Few comments/questions.
1] We also need to scale down the the v1 keda operator to 0 replicas so that deleted v1 HPA don't get recreated.
2] scaledjob crd has some issues, as I get error when I apply it -
$ kubectl apply -f https://github.com/kedacore/charts/tree/v2.2.0/keda/crds
error: error parsing https://github.com/kedacore/charts/tree/v2.2.0/keda/crds: error converting YAML to JSON: yaml: line 139: mapping values are not allowed in this context
It worked fine after yamlinting and then applying from local path.
3] With this approach, we have to manually apply v2 crds first and then later install helm chart for operator with --skip-crds option as far as I understood which could be a bit problematic considering the maintainability of chart and crds.

In all, this manual migration worked fine and thanks for the steps! 
But just wondering if there is a cleaner way available for v1 -> v2 migration by now ?

**Comment by tomkerkhove** [comment]
This will no longer happen
